## 공통 설정
spring:
  application:
    name: MichaelTest
  main:
    allow-bean-definition-overriding: true
server:
  port: 80

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    com.gme.gmeloanapi.proxy.OpenBankAccountProxy: DEBUG
    root: info

---
## local 설정
spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/michael_test?useSSL=false&useUnicode=true;
      username: michael
      password: michael!@34
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

---
## dev 설정
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/michael_test?useSSL=false&useUnicode=true;
      username: michael
      password: michael!@34
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

---
## prod 설정
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/michael_test?useSSL=false&useUnicode=true;
      username: michael
      password: michael!@34
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
