## 공통 설정
spring:
  application:
    name: MichaelTest
  main:
    allow-bean-definition-overriding: true
server:
  port: 80

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    com.gme.gmeloanapi.proxy.OpenBankAccountProxy: DEBUG
    root: info

---
## local 설정
spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
image:
  path: C:\\Image

---
## dev 설정
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

---
## prod 설정
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    finance:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://10.25.10.192:1433;databaseName=gfncdb;encrypt=false;
      username: wein_app
      password: NOiA7TSUukbX5hzQ920o93M89IO7GzTH
    core:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://10.25.12.100:1433;databaseName=FastMoneyPro_Remit;encrypt=false;
        username: GFNCAPP
        password: gfncapp123!@#